//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Scripts/Player/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Character"",
            ""id"": ""813bbde3-2d82-47a5-8554-ee2ba3fb8dd0"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b8b9111e-cad5-4794-aba1-f9c844818669"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryDisplayContext"",
                    ""type"": ""Button"",
                    ""id"": ""0cb7e908-d3df-474d-b44b-ebfae14d0de1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipSlot1"",
                    ""type"": ""Button"",
                    ""id"": ""aa9cd751-7d2b-40ca-b713-57d4d46d2afd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipSlot2"",
                    ""type"": ""Button"",
                    ""id"": ""02eece99-44c6-4fcd-bb8e-74203115fee9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EquipSlot3"",
                    ""type"": ""Button"",
                    ""id"": ""b61846bf-7cec-40ff-81f2-b9f9520c8293"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""efc313ed-af05-4ecc-8800-f1a12dfcccef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelAction"",
                    ""type"": ""Button"",
                    ""id"": ""994812ce-b516-441d-b3a3-10f84bbb6c07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Modifier1"",
                    ""type"": ""Button"",
                    ""id"": ""0dc57dde-961b-4ff7-85dc-1ba68b1ae4e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateSegment"",
                    ""type"": ""Button"",
                    ""id"": ""49f1bd15-755d-4cdd-b4fe-7e0b15fe7cb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""6fc93fce-c314-4ed9-b36b-2e5be64bd8da"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b060781b-c88a-4fa2-94b5-8db5bb3fd848"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""08334225-3f6a-4c11-b82c-8ccb06787c66"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""337cc383-160b-4172-a43f-ddb15f3fa961"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""80048989-beaa-4de2-a930-6300ac188292"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""144a77e7-bb77-42ba-b128-9748417a383d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryDisplayContext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6c2986e-6f20-4d46-aae9-c3232350107b"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipSlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76b0fdef-fd63-4351-b1e2-f17dedc8dcb4"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipSlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b63748c2-c622-4761-9864-036ef6c15a27"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EquipSlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""655d3548-65cc-4981-94a4-880754d53e24"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb8d717d-3929-4626-b283-6843a2ed36d2"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad00bef4-dc15-4015-9b5c-9725e14eaba3"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateSegment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae48e92d-062a-4a37-8a84-b90abf853d5c"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Modifier1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""a63b73d1-cae5-4ba3-867e-44bed6921846"",
            ""actions"": [
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""87e058c8-d478-4a7a-be98-acefa9594ade"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseScrollDelta"",
                    ""type"": ""Value"",
                    ""id"": ""607ba084-d62b-49f3-9e1b-5fc7dae2b395"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8ff6ebd0-e183-4798-9754-2a647c3e98f5"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d9b9d61-3691-4192-b09b-f848e409b3f6"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScrollDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Character
        m_Character = asset.FindActionMap("Character", throwIfNotFound: true);
        m_Character_Movement = m_Character.FindAction("Movement", throwIfNotFound: true);
        m_Character_InventoryDisplayContext = m_Character.FindAction("InventoryDisplayContext", throwIfNotFound: true);
        m_Character_EquipSlot1 = m_Character.FindAction("EquipSlot1", throwIfNotFound: true);
        m_Character_EquipSlot2 = m_Character.FindAction("EquipSlot2", throwIfNotFound: true);
        m_Character_EquipSlot3 = m_Character.FindAction("EquipSlot3", throwIfNotFound: true);
        m_Character_Action = m_Character.FindAction("Action", throwIfNotFound: true);
        m_Character_CancelAction = m_Character.FindAction("CancelAction", throwIfNotFound: true);
        m_Character_Modifier1 = m_Character.FindAction("Modifier1", throwIfNotFound: true);
        m_Character_RotateSegment = m_Character.FindAction("RotateSegment", throwIfNotFound: true);
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_MouseDelta = m_Camera.FindAction("MouseDelta", throwIfNotFound: true);
        m_Camera_MouseScrollDelta = m_Camera.FindAction("MouseScrollDelta", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Character
    private readonly InputActionMap m_Character;
    private ICharacterActions m_CharacterActionsCallbackInterface;
    private readonly InputAction m_Character_Movement;
    private readonly InputAction m_Character_InventoryDisplayContext;
    private readonly InputAction m_Character_EquipSlot1;
    private readonly InputAction m_Character_EquipSlot2;
    private readonly InputAction m_Character_EquipSlot3;
    private readonly InputAction m_Character_Action;
    private readonly InputAction m_Character_CancelAction;
    private readonly InputAction m_Character_Modifier1;
    private readonly InputAction m_Character_RotateSegment;
    public struct CharacterActions
    {
        private @PlayerControls m_Wrapper;
        public CharacterActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Character_Movement;
        public InputAction @InventoryDisplayContext => m_Wrapper.m_Character_InventoryDisplayContext;
        public InputAction @EquipSlot1 => m_Wrapper.m_Character_EquipSlot1;
        public InputAction @EquipSlot2 => m_Wrapper.m_Character_EquipSlot2;
        public InputAction @EquipSlot3 => m_Wrapper.m_Character_EquipSlot3;
        public InputAction @Action => m_Wrapper.m_Character_Action;
        public InputAction @CancelAction => m_Wrapper.m_Character_CancelAction;
        public InputAction @Modifier1 => m_Wrapper.m_Character_Modifier1;
        public InputAction @RotateSegment => m_Wrapper.m_Character_RotateSegment;
        public InputActionMap Get() { return m_Wrapper.m_Character; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterActions set) { return set.Get(); }
        public void SetCallbacks(ICharacterActions instance)
        {
            if (m_Wrapper.m_CharacterActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnMovement;
                @InventoryDisplayContext.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnInventoryDisplayContext;
                @InventoryDisplayContext.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnInventoryDisplayContext;
                @InventoryDisplayContext.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnInventoryDisplayContext;
                @EquipSlot1.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot1;
                @EquipSlot1.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot1;
                @EquipSlot1.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot1;
                @EquipSlot2.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot2;
                @EquipSlot2.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot2;
                @EquipSlot2.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot2;
                @EquipSlot3.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot3;
                @EquipSlot3.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot3;
                @EquipSlot3.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnEquipSlot3;
                @Action.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnAction;
                @CancelAction.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnCancelAction;
                @CancelAction.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnCancelAction;
                @CancelAction.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnCancelAction;
                @Modifier1.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModifier1;
                @Modifier1.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModifier1;
                @Modifier1.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnModifier1;
                @RotateSegment.started -= m_Wrapper.m_CharacterActionsCallbackInterface.OnRotateSegment;
                @RotateSegment.performed -= m_Wrapper.m_CharacterActionsCallbackInterface.OnRotateSegment;
                @RotateSegment.canceled -= m_Wrapper.m_CharacterActionsCallbackInterface.OnRotateSegment;
            }
            m_Wrapper.m_CharacterActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @InventoryDisplayContext.started += instance.OnInventoryDisplayContext;
                @InventoryDisplayContext.performed += instance.OnInventoryDisplayContext;
                @InventoryDisplayContext.canceled += instance.OnInventoryDisplayContext;
                @EquipSlot1.started += instance.OnEquipSlot1;
                @EquipSlot1.performed += instance.OnEquipSlot1;
                @EquipSlot1.canceled += instance.OnEquipSlot1;
                @EquipSlot2.started += instance.OnEquipSlot2;
                @EquipSlot2.performed += instance.OnEquipSlot2;
                @EquipSlot2.canceled += instance.OnEquipSlot2;
                @EquipSlot3.started += instance.OnEquipSlot3;
                @EquipSlot3.performed += instance.OnEquipSlot3;
                @EquipSlot3.canceled += instance.OnEquipSlot3;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @CancelAction.started += instance.OnCancelAction;
                @CancelAction.performed += instance.OnCancelAction;
                @CancelAction.canceled += instance.OnCancelAction;
                @Modifier1.started += instance.OnModifier1;
                @Modifier1.performed += instance.OnModifier1;
                @Modifier1.canceled += instance.OnModifier1;
                @RotateSegment.started += instance.OnRotateSegment;
                @RotateSegment.performed += instance.OnRotateSegment;
                @RotateSegment.canceled += instance.OnRotateSegment;
            }
        }
    }
    public CharacterActions @Character => new CharacterActions(this);

    // Camera
    private readonly InputActionMap m_Camera;
    private ICameraActions m_CameraActionsCallbackInterface;
    private readonly InputAction m_Camera_MouseDelta;
    private readonly InputAction m_Camera_MouseScrollDelta;
    public struct CameraActions
    {
        private @PlayerControls m_Wrapper;
        public CameraActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseDelta => m_Wrapper.m_Camera_MouseDelta;
        public InputAction @MouseScrollDelta => m_Wrapper.m_Camera_MouseScrollDelta;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void SetCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterface != null)
            {
                @MouseDelta.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMouseDelta;
                @MouseScrollDelta.started -= m_Wrapper.m_CameraActionsCallbackInterface.OnMouseScrollDelta;
                @MouseScrollDelta.performed -= m_Wrapper.m_CameraActionsCallbackInterface.OnMouseScrollDelta;
                @MouseScrollDelta.canceled -= m_Wrapper.m_CameraActionsCallbackInterface.OnMouseScrollDelta;
            }
            m_Wrapper.m_CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseDelta.started += instance.OnMouseDelta;
                @MouseDelta.performed += instance.OnMouseDelta;
                @MouseDelta.canceled += instance.OnMouseDelta;
                @MouseScrollDelta.started += instance.OnMouseScrollDelta;
                @MouseScrollDelta.performed += instance.OnMouseScrollDelta;
                @MouseScrollDelta.canceled += instance.OnMouseScrollDelta;
            }
        }
    }
    public CameraActions @Camera => new CameraActions(this);
    public interface ICharacterActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnInventoryDisplayContext(InputAction.CallbackContext context);
        void OnEquipSlot1(InputAction.CallbackContext context);
        void OnEquipSlot2(InputAction.CallbackContext context);
        void OnEquipSlot3(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnCancelAction(InputAction.CallbackContext context);
        void OnModifier1(InputAction.CallbackContext context);
        void OnRotateSegment(InputAction.CallbackContext context);
    }
    public interface ICameraActions
    {
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMouseScrollDelta(InputAction.CallbackContext context);
    }
}
